<?php

namespace TngWorkshop\BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoardMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardMessageRepository extends EntityRepository
{
}
