<?php

namespace TngWorkshop\BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoardTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardTagRepository extends EntityRepository
{
    /**
     * @param string $tag
     * @return BoardTag|null
     */
    public function get($tag)
    {
        return $this->findOneBy(array('tag' => $tag));
    }

    /**
     * @return BoardTag[]
     */
    public function getAll()
    {
        return $this->findBy(array(), array('tag' => 'ASC'));
    }
}
